package com.techzone.login;

import com.techzone.db.DBConnection;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class ResetQuestions extends javax.swing.JFrame {

    
    public ResetQuestions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQ1 = new javax.swing.JTextField();
        txtAns1 = new javax.swing.JTextField();
        txtQ2 = new javax.swing.JTextField();
        txtAns2 = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnShowsec = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recover Password");
        setMinimumSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 26)); // NOI18N
        jLabel1.setText("Answer the Security Questions");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 42));

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel2.setText("User ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 70, 23));

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 28)); // NOI18N
        jLabel7.setText("to Reset Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        txtUid.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        getContentPane().add(txtUid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 280, 30));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel3.setText("Question 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 31));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel4.setText("Answer 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 138, 31));

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel5.setText("Question 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 138, 31));

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        jLabel6.setText("Answer 2");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 138, 31));

        txtQ1.setEditable(false);
        txtQ1.setFont(new java.awt.Font("Montserrat", 2, 14)); // NOI18N
        getContentPane().add(txtQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 280, 31));

        txtAns1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        getContentPane().add(txtAns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 280, 31));

        txtQ2.setEditable(false);
        txtQ2.setFont(new java.awt.Font("Montserrat", 2, 14)); // NOI18N
        getContentPane().add(txtQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 280, 31));

        txtAns2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        getContentPane().add(txtAns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 280, 31));

        btnConfirm.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 110, 36));

        btnLogin.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnLogin.setText("Back");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, 36));

        btnShowsec.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        btnShowsec.setText("Show Security Questions");
        btnShowsec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowsecActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowsec, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 230, 40));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 450, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowsecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowsecActionPerformed
        String ui=txtUid.getText();
         DBConnection con1=new DBConnection();
          con1.getConnection();
        
        try {
            Statement s1=con1.getConnection().createStatement();
            ResultSet rs1=s1.executeQuery("select uid,q1,a1,q2,a2 from signup where uid='"+ui+"'");
            while(rs1.next()){
                txtQ1.setText(rs1.getString(2));
                txtQ2.setText(rs1.getString(4));
            }
            }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }
        if(txtQ1.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "User ID Not Found", "Error", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnShowsecActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        String a2=txtAns2.getText();
        String a1=txtAns1.getText();
        String ui=txtUid.getText();
        DBConnection con=new DBConnection();
        Connection c =con.getConnection();
        
        try {
            Statement s1=con.getConnection().createStatement();
            ResultSet rs1=s1.executeQuery("select uid,q1,a1,q2,a2 from signup where uid='"+ui+"'");
            while(rs1.next()){
                if(rs1.getString(3).equalsIgnoreCase(a1)&&rs1.getString(5).equalsIgnoreCase(a2)){
                   Newpwd np=new Newpwd();
                   Newpwd.txtUid.setText(ui);
                   np.setVisible(true);
                   this.setVisible(false);
       }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Wrong Answers Entered.Please check again", "Error", ERROR_MESSAGE);
       }    
                
            }
            }
        catch(SQLException e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetQuestions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnShowsec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAns1;
    private javax.swing.JTextField txtAns2;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ2;
    public static javax.swing.JTextField txtUid;
    // End of variables declaration//GEN-END:variables
}
